### ISSUE TITLE
[request] Visualizzazione dati per provincia

### ISSUE THREAD

**Issue by jokerigno** [PicciMario/covidbot#1]
Ciao Mario,

innaniziutto complimenti perchè il tuo bot è uno dei più chiari.

Sempre in termini di chiarezza pensi sia possibile fare in modo che il bot riporti anche lo status di una provincia (dati presenti sul repository originale?) 

Questo differenzierebbe il tuo dagli altri che "inondano" l'utente di dati non richiesti (mi interessa principalmente la situazione nazionale e quella della mia regione).

**Comment by PicciMario** [comment]
Grazie mille per i complimenti :-) 
Adesso sto lavorando sulla visualizzazione dei dati per regione; appena finito questo step credo che mi dedicherò alla visualizzazione per provincia.

**Comment by PicciMario** [comment]
Fatto! Disponibili dati per regione e per provincia.
